/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package gui;
import controller.AccessController;
import entity.Access;
import javax.swing.JOptionPane;

/**
 *
 * @author Marjorie
 */
public class FrmRegister extends javax.swing.JFrame {
    
    private Access access;
    private Access loged;
    private AccessController acC = new AccessController();
    
    public FrmRegister() {
        initComponents();
    }
    
    /**
     * Creates new form FrmRegister
     * @param a
     */
    public FrmRegister(Access a) {
        initComponents();
        
        if (a == null) {
            btnSearchRegister.setVisible(false);
            btnDeleteRegister.setVisible(false);
            btnUpdateRegister.setVisible(false);
            chkPermission.setVisible(false);
        }
        else {
            if (a.getPermission() == 0) {
                btnNewRegister.setVisible(false);
                btnSaveRegister.setVisible(false);
                btnSearchRegister.setVisible(false);
                btnDeleteRegister.setVisible(false);
                chkPermission.setVisible(false);
            }
            
            loged = a;
            access = a;
            fillFieldsRegister();
        }
    }
    
    public void limpaCamposRegister() {
        access = null;
        txtUsername.setText("");
        txtPassword.setText("");
        txtConfirmPassword.setText("");
        chkPermission.setSelected(false);
    }
    
    public void habilitaDesabilitaCamposRegister(boolean habilita) {
        txtUsername.setEnabled(habilita);
        txtPassword.setEnabled(habilita);
        txtConfirmPassword.setEnabled(habilita);
        chkPermission.setEnabled(habilita);
        btnSearchRegister.setEnabled(habilita);
        btnSearchRegister.setSelected(false);
    }
    
    public void fillFieldsRegister() {
        txtUsername.setText(access.getUsername());
        chkPermission.setSelected(access.getPermission() == 1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpRegister = new javax.swing.JPanel();
        tbAdventureGear = new javax.swing.JToolBar();
        btnNewRegister = new javax.swing.JButton();
        btnUpdateRegister = new javax.swing.JButton();
        btnDeleteRegister = new javax.swing.JButton();
        btnSaveRegister = new javax.swing.JButton();
        btnCancelRegister = new javax.swing.JButton();
        btnExitRegister = new javax.swing.JButton();
        lblUsername = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        lblPassword = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        lblConfirmPassword = new javax.swing.JLabel();
        txtConfirmPassword = new javax.swing.JPasswordField();
        chkPermission = new javax.swing.JCheckBox();
        btnSearchRegister = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Register User");
        setResizable(false);

        tbAdventureGear.setRollover(true);

        btnNewRegister.setText("New");
        btnNewRegister.setFocusable(false);
        btnNewRegister.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNewRegister.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNewRegister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNewRegisterMouseClicked(evt);
            }
        });
        tbAdventureGear.add(btnNewRegister);

        btnUpdateRegister.setText("Update");
        btnUpdateRegister.setFocusable(false);
        btnUpdateRegister.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnUpdateRegister.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnUpdateRegister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUpdateRegisterMouseClicked(evt);
            }
        });
        tbAdventureGear.add(btnUpdateRegister);

        btnDeleteRegister.setText("Delete");
        btnDeleteRegister.setFocusable(false);
        btnDeleteRegister.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDeleteRegister.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDeleteRegister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDeleteRegisterMouseClicked(evt);
            }
        });
        tbAdventureGear.add(btnDeleteRegister);

        btnSaveRegister.setText("Save");
        btnSaveRegister.setFocusable(false);
        btnSaveRegister.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSaveRegister.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSaveRegister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSaveRegisterMouseClicked(evt);
            }
        });
        tbAdventureGear.add(btnSaveRegister);

        btnCancelRegister.setText("Cancel");
        btnCancelRegister.setFocusable(false);
        btnCancelRegister.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCancelRegister.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCancelRegister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelRegisterMouseClicked(evt);
            }
        });
        tbAdventureGear.add(btnCancelRegister);

        btnExitRegister.setText("Exit");
        btnExitRegister.setFocusable(false);
        btnExitRegister.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnExitRegister.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnExitRegister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExitRegisterMouseClicked(evt);
            }
        });
        tbAdventureGear.add(btnExitRegister);

        lblUsername.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblUsername.setText("Username");
        lblUsername.setName("lblUsername"); // NOI18N

        txtUsername.setToolTipText("Type your username");
        txtUsername.setName("txtUsername"); // NOI18N

        lblPassword.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblPassword.setText("Password");
        lblPassword.setName("lblPassword"); // NOI18N

        txtPassword.setToolTipText("Type your password");
        txtPassword.setName("txtPassword"); // NOI18N

        lblConfirmPassword.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblConfirmPassword.setText("Confirm Password");
        lblConfirmPassword.setName("lblPassword"); // NOI18N

        txtConfirmPassword.setToolTipText("Type your password");
        txtConfirmPassword.setName("txtPassword"); // NOI18N

        chkPermission.setText("Give Permission");

        btnSearchRegister.setText("Search");
        btnSearchRegister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSearchRegisterMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jpRegisterLayout = new javax.swing.GroupLayout(jpRegister);
        jpRegister.setLayout(jpRegisterLayout);
        jpRegisterLayout.setHorizontalGroup(
            jpRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpRegisterLayout.createSequentialGroup()
                .addGap(0, 34, Short.MAX_VALUE)
                .addGroup(jpRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpRegisterLayout.createSequentialGroup()
                        .addGroup(jpRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jpRegisterLayout.createSequentialGroup()
                                .addGroup(jpRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblPassword)
                                    .addComponent(lblUsername))
                                .addGap(18, 18, 18)
                                .addGroup(jpRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtUsername)
                                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jpRegisterLayout.createSequentialGroup()
                                .addComponent(lblConfirmPassword)
                                .addGap(18, 18, 18)
                                .addGroup(jpRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(chkPermission)
                                    .addComponent(txtConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnSearchRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(69, 69, 69))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpRegisterLayout.createSequentialGroup()
                        .addComponent(tbAdventureGear, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51))))
        );
        jpRegisterLayout.setVerticalGroup(
            jpRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpRegisterLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jpRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsername)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPassword)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblConfirmPassword)
                    .addComponent(txtConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chkPermission)
                .addGap(29, 29, 29)
                .addComponent(btnSearchRegister)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(tbAdventureGear, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpRegister, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpRegister, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnNewRegisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNewRegisterMouseClicked
        if (btnNewRegister.isEnabled()) {
            limpaCamposRegister();
            habilitaDesabilitaCamposRegister(true);

            btnNewRegister.setEnabled(false);
            btnUpdateRegister.setEnabled(false);
            btnDeleteRegister.setEnabled(false);
            btnCancelRegister.setEnabled(true);
            btnSaveRegister.setEnabled(true);
            btnExitRegister.setEnabled(false);
        }
    }//GEN-LAST:event_btnNewRegisterMouseClicked

    private void btnUpdateRegisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateRegisterMouseClicked
        if (btnUpdateRegister.isEnabled()) {
            String passkey = new String(txtPassword.getPassword());
            int permission = 0;
            
            if (!passkey.equals(new String(txtConfirmPassword.getPassword()))) {
                JOptionPane.showMessageDialog(jpRegister, "invalid passkey confirmation");
            }
            else {
                if (chkPermission.isVisible()) permission = chkPermission.isSelected()?1:0;
                access = new Access(access.getIdAccess(), access.getUsername(), 
                        passkey, permission);

                if (acC.update(access) == 1) {
                    JOptionPane.showMessageDialog(jpRegister, "success!");
                    limpaCamposRegister();
                    habilitaDesabilitaCamposRegister(rootPaneCheckingEnabled);

                    btnNewRegister.setEnabled(true);
                    btnUpdateRegister.setEnabled(false);
                    btnDeleteRegister.setEnabled(false);
                    btnCancelRegister.setEnabled(false);
                    btnSaveRegister.setEnabled(false);
                    btnExitRegister.setEnabled(true);

                    if (loged.getPermission() == 0) {
                        this.setVisible(false);
                    }
                }
                else {
                    JOptionPane.showMessageDialog(jpRegister, "error");
                }
            }
        }
    }//GEN-LAST:event_btnUpdateRegisterMouseClicked

    private void btnDeleteRegisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteRegisterMouseClicked
        if (btnDeleteRegister.isEnabled()) {
            if (acC.remove(access) == 1) {
                JOptionPane.showMessageDialog(jpRegister, "success!");
                limpaCamposRegister();
                habilitaDesabilitaCamposRegister(false);

                btnNewRegister.setEnabled(true);
                btnUpdateRegister.setEnabled(false);
                btnDeleteRegister.setEnabled(false);
                btnCancelRegister.setEnabled(false);
                btnSaveRegister.setEnabled(false);
                btnExitRegister.setEnabled(true);
            }
            else {
                JOptionPane.showMessageDialog(jpRegister, "error");
            }
        }
    }//GEN-LAST:event_btnDeleteRegisterMouseClicked

    private void btnSaveRegisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSaveRegisterMouseClicked
        if (btnSaveRegister.isEnabled()) {
            String passkey = new String(txtPassword.getPassword());
            int permission = 0;
            System.out.println(passkey);
            System.out.println(new String(txtConfirmPassword.getPassword()));
            if (acC.getByLogin(txtUsername.getText()) != null) {
                JOptionPane.showMessageDialog(jpRegister, "invalid login! choose another one");
            }
            else {
                if (!passkey.equals(new String(txtConfirmPassword.getPassword()))) {
                    JOptionPane.showMessageDialog(jpRegister, "invalid passkey confirmation");
                }
                else {
                    if (chkPermission.isVisible()) permission = chkPermission.isSelected()?1:0;
                    access = new Access(txtUsername.getText(), passkey, permission);

                    if (acC.insert(access) == 1) {
                        JOptionPane.showMessageDialog(jpRegister, "success!");

                        limpaCamposRegister();
                        habilitaDesabilitaCamposRegister(false);

                        //gerenciando os botoes
                        btnNewRegister.setEnabled(true);
                        btnUpdateRegister.setEnabled(false);
                        btnDeleteRegister.setEnabled(false);
                        btnCancelRegister.setEnabled(false);
                        btnSaveRegister.setEnabled(false);
                        btnExitRegister.setEnabled(true);

                        if (loged == null) {
                            this.setVisible(false);
                        }
                        else {
                            if (loged.getPermission() == 0) {
                                this.setVisible(false);
                            }
                        }
                    }
                    else {
                        JOptionPane.showMessageDialog(jpRegister, "error");
                    }
                }
            }
        }
    }//GEN-LAST:event_btnSaveRegisterMouseClicked

    private void btnCancelRegisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelRegisterMouseClicked
        if (btnCancelRegister.isEnabled()) {
            limpaCamposRegister();
            habilitaDesabilitaCamposRegister(true);
            //Habilitando a barra de ferramentas
            btnNewRegister.setEnabled(false);
            btnUpdateRegister.setEnabled(false);
            btnDeleteRegister.setEnabled(false);
            btnCancelRegister.setEnabled(true);
            btnSaveRegister.setEnabled(true);
            btnExitRegister.setEnabled(true);
        }
    }//GEN-LAST:event_btnCancelRegisterMouseClicked

    private void btnSearchRegisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchRegisterMouseClicked
        if (btnSearchRegister.isEnabled()) {
            access = acC.getByLogin(txtUsername.getText());
            
            if (access == null) {
                JOptionPane.showMessageDialog(jpRegister, "invalid login");
                btnSearchRegister.setSelected(false);
            }
            else {
                fillFieldsRegister();
                txtUsername.setEnabled(false);
                btnSearchRegister.setEnabled(false);

                btnNewRegister.setEnabled(false);
                btnUpdateRegister.setEnabled(true);
                btnDeleteRegister.setEnabled(true);
                btnCancelRegister.setEnabled(true);
                btnSaveRegister.setEnabled(false);
                btnExitRegister.setEnabled(true);
            }
        }
    }//GEN-LAST:event_btnSearchRegisterMouseClicked

    private void btnExitRegisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitRegisterMouseClicked
        System.exit(0);
    }//GEN-LAST:event_btnExitRegisterMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmRegister().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelRegister;
    private javax.swing.JButton btnDeleteRegister;
    private javax.swing.JButton btnExitRegister;
    private javax.swing.JButton btnNewRegister;
    private javax.swing.JButton btnSaveRegister;
    private javax.swing.JToggleButton btnSearchRegister;
    private javax.swing.JButton btnUpdateRegister;
    private javax.swing.JCheckBox chkPermission;
    private javax.swing.JPanel jpRegister;
    private javax.swing.JLabel lblConfirmPassword;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JToolBar tbAdventureGear;
    private javax.swing.JPasswordField txtConfirmPassword;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
