/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

/**
 *
 * @author aluno
 */
public class frmVault extends javax.swing.JFrame {

    /**
     * Creates new form frmVault
     */
    public frmVault() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpVault = new javax.swing.JPanel();
        jtVault = new javax.swing.JTabbedPane();
        jpAdventureGear = new javax.swing.JPanel();
        lblDescriptionGear = new javax.swing.JLabel();
        lblTypeGear = new javax.swing.JLabel();
        txtTypeGear = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescription = new javax.swing.JTextArea();
        tbAdventureGear = new javax.swing.JToolBar();
        btnNew = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblGear = new javax.swing.JTable();
        jpArmor = new javax.swing.JPanel();
        lblTypeArmor = new javax.swing.JLabel();
        lblACBonus = new javax.swing.JLabel();
        lblModifierArmor = new javax.swing.JLabel();
        lblStealthDArmor = new javax.swing.JLabel();
        lblStrenghtRArmor = new javax.swing.JLabel();
        txtTypeArmor = new javax.swing.JTextField();
        txtACBonus = new javax.swing.JTextField();
        txtModifierArmor = new javax.swing.JTextField();
        txtStealthDArmor = new javax.swing.JTextField();
        txtStrenghtRArmor = new javax.swing.JTextField();
        tbArmor = new javax.swing.JToolBar();
        btnNewArmor = new javax.swing.JButton();
        btnUpdateArmor = new javax.swing.JButton();
        btnDeleteArmor = new javax.swing.JButton();
        btnSaveArmor = new javax.swing.JButton();
        btnCancelArmor = new javax.swing.JButton();
        btnExitArmor = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jpWeapon = new javax.swing.JPanel();
        jpMonster = new javax.swing.JPanel();
        jpSpell = new javax.swing.JPanel();
        jpAttribute = new javax.swing.JPanel();
        jpEquipment = new javax.swing.JPanel();
        jpItem = new javax.swing.JPanel();
        jpAttack = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Vault");
        setName("jfVault"); // NOI18N

        jpAdventureGear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpAdventureGearMouseClicked(evt);
            }
        });
        jpAdventureGear.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jpAdventureGearComponentShown(evt);
            }
        });

        lblDescriptionGear.setText("Description :");

        lblTypeGear.setText("Gear Type :");

        txtDescription.setColumns(20);
        txtDescription.setRows(5);
        jScrollPane1.setViewportView(txtDescription);

        tbAdventureGear.setRollover(true);

        btnNew.setText("New");
        btnNew.setFocusable(false);
        btnNew.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNew.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNew.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNewMouseClicked(evt);
            }
        });
        tbAdventureGear.add(btnNew);

        btnUpdate.setText("Update");
        btnUpdate.setFocusable(false);
        btnUpdate.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnUpdate.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUpdateMouseClicked(evt);
            }
        });
        tbAdventureGear.add(btnUpdate);

        btnDelete.setText("Delete");
        btnDelete.setFocusable(false);
        btnDelete.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDelete.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDeleteMouseClicked(evt);
            }
        });
        tbAdventureGear.add(btnDelete);

        btnSave.setText("Save");
        btnSave.setFocusable(false);
        btnSave.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSave.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSaveMouseClicked(evt);
            }
        });
        tbAdventureGear.add(btnSave);

        btnCancel.setText("Cancel");
        btnCancel.setFocusable(false);
        btnCancel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCancel.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelMouseClicked(evt);
            }
        });
        tbAdventureGear.add(btnCancel);

        btnExit.setText("Exit");
        btnExit.setFocusable(false);
        btnExit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnExit.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tbAdventureGear.add(btnExit);

        tblGear.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblGear);

        javax.swing.GroupLayout jpAdventureGearLayout = new javax.swing.GroupLayout(jpAdventureGear);
        jpAdventureGear.setLayout(jpAdventureGearLayout);
        jpAdventureGearLayout.setHorizontalGroup(
            jpAdventureGearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpAdventureGearLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jpAdventureGearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpAdventureGearLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jpAdventureGearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTypeGear, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tbAdventureGear, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpAdventureGearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblDescriptionGear)
                        .addComponent(lblTypeGear)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpAdventureGearLayout.setVerticalGroup(
            jpAdventureGearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpAdventureGearLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jpAdventureGearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpAdventureGearLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(70, Short.MAX_VALUE))
                    .addGroup(jpAdventureGearLayout.createSequentialGroup()
                        .addComponent(lblDescriptionGear)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblTypeGear)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTypeGear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(tbAdventureGear, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))))
        );

        jtVault.addTab("Adventure Gear", jpAdventureGear);

        jpArmor.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jpArmorComponentShown(evt);
            }
        });

        lblTypeArmor.setText("Armor Type :");

        lblACBonus.setText("AC Bonus Base :");

        lblModifierArmor.setText("Modifier :");

        lblStealthDArmor.setText("Stealth Disadvantage :");

        lblStrenghtRArmor.setText("Strenght Requirement :");

        tbArmor.setRollover(true);

        btnNewArmor.setText("New");
        btnNewArmor.setFocusable(false);
        btnNewArmor.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNewArmor.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNewArmor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNewArmorMouseClicked(evt);
            }
        });
        tbArmor.add(btnNewArmor);

        btnUpdateArmor.setText("Update");
        btnUpdateArmor.setFocusable(false);
        btnUpdateArmor.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnUpdateArmor.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnUpdateArmor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUpdateArmorMouseClicked(evt);
            }
        });
        tbArmor.add(btnUpdateArmor);

        btnDeleteArmor.setText("Delete");
        btnDeleteArmor.setFocusable(false);
        btnDeleteArmor.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDeleteArmor.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDeleteArmor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDeleteArmorMouseClicked(evt);
            }
        });
        tbArmor.add(btnDeleteArmor);

        btnSaveArmor.setText("Save");
        btnSaveArmor.setFocusable(false);
        btnSaveArmor.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSaveArmor.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSaveArmor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSaveArmorMouseClicked(evt);
            }
        });
        tbArmor.add(btnSaveArmor);

        btnCancelArmor.setText("Cancel");
        btnCancelArmor.setFocusable(false);
        btnCancelArmor.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCancelArmor.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCancelArmor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelArmorMouseClicked(evt);
            }
        });
        tbArmor.add(btnCancelArmor);

        btnExitArmor.setText("Exit");
        btnExitArmor.setFocusable(false);
        btnExitArmor.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnExitArmor.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tbArmor.add(btnExitArmor);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable1);

        javax.swing.GroupLayout jpArmorLayout = new javax.swing.GroupLayout(jpArmor);
        jpArmor.setLayout(jpArmorLayout);
        jpArmorLayout.setHorizontalGroup(
            jpArmorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpArmorLayout.createSequentialGroup()
                .addGroup(jpArmorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpArmorLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(jpArmorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpArmorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblStrenghtRArmor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblModifierArmor)
                                .addComponent(lblACBonus)
                                .addComponent(lblTypeArmor)
                                .addGroup(jpArmorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtStealthDArmor, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblStealthDArmor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtModifierArmor, javax.swing.GroupLayout.Alignment.LEADING))
                                .addComponent(txtStrenghtRArmor))
                            .addGroup(jpArmorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtTypeArmor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                                .addComponent(txtACBonus, javax.swing.GroupLayout.Alignment.LEADING))))
                    .addGroup(jpArmorLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(tbArmor, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );
        jpArmorLayout.setVerticalGroup(
            jpArmorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpArmorLayout.createSequentialGroup()
                .addGroup(jpArmorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpArmorLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(lblTypeArmor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTypeArmor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblACBonus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtACBonus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblModifierArmor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtModifierArmor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblStealthDArmor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtStealthDArmor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblStrenghtRArmor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtStrenghtRArmor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(tbArmor, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpArmorLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jtVault.addTab("Armor", jpArmor);

        javax.swing.GroupLayout jpWeaponLayout = new javax.swing.GroupLayout(jpWeapon);
        jpWeapon.setLayout(jpWeaponLayout);
        jpWeaponLayout.setHorizontalGroup(
            jpWeaponLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 851, Short.MAX_VALUE)
        );
        jpWeaponLayout.setVerticalGroup(
            jpWeaponLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 464, Short.MAX_VALUE)
        );

        jtVault.addTab("Weapon", jpWeapon);

        javax.swing.GroupLayout jpMonsterLayout = new javax.swing.GroupLayout(jpMonster);
        jpMonster.setLayout(jpMonsterLayout);
        jpMonsterLayout.setHorizontalGroup(
            jpMonsterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 851, Short.MAX_VALUE)
        );
        jpMonsterLayout.setVerticalGroup(
            jpMonsterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 464, Short.MAX_VALUE)
        );

        jtVault.addTab("Monster", jpMonster);

        javax.swing.GroupLayout jpSpellLayout = new javax.swing.GroupLayout(jpSpell);
        jpSpell.setLayout(jpSpellLayout);
        jpSpellLayout.setHorizontalGroup(
            jpSpellLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 851, Short.MAX_VALUE)
        );
        jpSpellLayout.setVerticalGroup(
            jpSpellLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 464, Short.MAX_VALUE)
        );

        jtVault.addTab("Spell", jpSpell);

        javax.swing.GroupLayout jpAttributeLayout = new javax.swing.GroupLayout(jpAttribute);
        jpAttribute.setLayout(jpAttributeLayout);
        jpAttributeLayout.setHorizontalGroup(
            jpAttributeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 851, Short.MAX_VALUE)
        );
        jpAttributeLayout.setVerticalGroup(
            jpAttributeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 464, Short.MAX_VALUE)
        );

        jtVault.addTab("Attribute", jpAttribute);

        javax.swing.GroupLayout jpEquipmentLayout = new javax.swing.GroupLayout(jpEquipment);
        jpEquipment.setLayout(jpEquipmentLayout);
        jpEquipmentLayout.setHorizontalGroup(
            jpEquipmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 851, Short.MAX_VALUE)
        );
        jpEquipmentLayout.setVerticalGroup(
            jpEquipmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 464, Short.MAX_VALUE)
        );

        jtVault.addTab("Equipment", jpEquipment);

        javax.swing.GroupLayout jpItemLayout = new javax.swing.GroupLayout(jpItem);
        jpItem.setLayout(jpItemLayout);
        jpItemLayout.setHorizontalGroup(
            jpItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 851, Short.MAX_VALUE)
        );
        jpItemLayout.setVerticalGroup(
            jpItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 464, Short.MAX_VALUE)
        );

        jtVault.addTab("Item", jpItem);

        javax.swing.GroupLayout jpAttackLayout = new javax.swing.GroupLayout(jpAttack);
        jpAttack.setLayout(jpAttackLayout);
        jpAttackLayout.setHorizontalGroup(
            jpAttackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 851, Short.MAX_VALUE)
        );
        jpAttackLayout.setVerticalGroup(
            jpAttackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 464, Short.MAX_VALUE)
        );

        jtVault.addTab("Attack", jpAttack);

        javax.swing.GroupLayout jpVaultLayout = new javax.swing.GroupLayout(jpVault);
        jpVault.setLayout(jpVaultLayout);
        jpVaultLayout.setHorizontalGroup(
            jpVaultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 859, Short.MAX_VALUE)
            .addGroup(jpVaultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jpVaultLayout.createSequentialGroup()
                    .addGap(1, 1, 1)
                    .addComponent(jtVault)
                    .addGap(2, 2, 2)))
        );
        jpVaultLayout.setVerticalGroup(
            jpVaultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 514, Short.MAX_VALUE)
            .addGroup(jpVaultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jpVaultLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jtVault)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpVault, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpVault, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jpAdventureGearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpAdventureGearMouseClicked
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jpAdventureGearMouseClicked

    private void jpAdventureGearComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jpAdventureGearComponentShown
        // TODO add your handling code here:
         //Desabilitando as caixas de edição
        txtDescription.setEnabled(false);
        txtTypeGear.setEnabled(false);
        
        //Habilitando a barra de ferramentas
        btnNew.setEnabled(true);
        btnUpdate.setEnabled(true);
        btnDelete.setEnabled(true);
        btnCancel.setEnabled(false);
        btnSave.setEnabled(false);
        btnExit.setEnabled(true);
    }//GEN-LAST:event_jpAdventureGearComponentShown

    private void btnNewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNewMouseClicked
        // TODO add your handling code here:
        txtDescription.setEnabled(true);
        txtTypeGear.setEnabled(true);
        txtDescription.setText("");
        txtTypeGear.setText("");
        
        btnNew.setEnabled(false);
        btnUpdate.setEnabled(false);
        btnDelete.setEnabled(false);
        btnCancel.setEnabled(true);
        btnSave.setEnabled(true);
        btnExit.setEnabled(false);
    }//GEN-LAST:event_btnNewMouseClicked

    private void btnUpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateMouseClicked
        // TODO add your handling code here:
        txtDescription.setEnabled(true);
        txtTypeGear.setEnabled(true);
        
        btnNew.setEnabled(false);
        btnUpdate.setEnabled(false);
        btnDelete.setEnabled(false);
        btnCancel.setEnabled(true);
        btnSave.setEnabled(true);
        btnExit.setEnabled(false);
    }//GEN-LAST:event_btnUpdateMouseClicked

    private void btnDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteMouseClicked
        // TODO add your handling code here:
        txtDescription.setEnabled(true);
        txtTypeGear.setEnabled(true);
        txtDescription.setText("");
        txtTypeGear.setText("");
        
        btnNew.setEnabled(false);
        btnUpdate.setEnabled(false);
        btnDelete.setEnabled(false);
        btnCancel.setEnabled(true);
        btnSave.setEnabled(true);
        btnExit.setEnabled(false);
    }//GEN-LAST:event_btnDeleteMouseClicked

    private void btnSaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSaveMouseClicked
        // TODO add your handling code here:
        txtDescription.setEnabled(false);
        txtTypeGear.setEnabled(false);
        txtDescription.setText("");
        txtTypeGear.setText("");
        
        btnNew.setEnabled(true);
        btnUpdate.setEnabled(true);
        btnDelete.setEnabled(true);
        btnCancel.setEnabled(false);
        btnSave.setEnabled(false);
        btnExit.setEnabled(true);
    }//GEN-LAST:event_btnSaveMouseClicked

    private void btnCancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelMouseClicked
        // TODO add your handling code here:
        txtDescription.setEnabled(false);
        txtTypeGear.setEnabled(false);
        txtDescription.setText("");
        txtTypeGear.setText("");
        //Habilitando a barra de ferramentas
        btnNew.setEnabled(true);
        btnUpdate.setEnabled(true);
        btnDelete.setEnabled(true);
        btnCancel.setEnabled(false);
        btnSave.setEnabled(false);
        btnExit.setEnabled(true);
    }//GEN-LAST:event_btnCancelMouseClicked

    private void jpArmorComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jpArmorComponentShown
        // TODO add your handling code here:
        txtTypeArmor.setEnabled(false);
        txtACBonus.setEnabled(false);
        txtModifierArmor.setEnabled(false);
        txtStealthDArmor.setEnabled(false);
        txtStrenghtRArmor.setEnabled(false);
        
        btnNewArmor.setEnabled(true);
        btnUpdateArmor.setEnabled(true);
        btnDeleteArmor.setEnabled(true);
        btnCancelArmor.setEnabled(false);
        btnSaveArmor.setEnabled(false);
        btnExitArmor.setEnabled(true);
    }//GEN-LAST:event_jpArmorComponentShown

    private void btnNewArmorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNewArmorMouseClicked
        // TODO add your handling code here:
        txtACBonus.setEnabled(true);
        txtModifierArmor.setEnabled(true);
        txtStealthDArmor.setEnabled(true);
        txtStrenghtRArmor.setEnabled(true);
        txtTypeArmor.setEnabled(true);
        txtACBonus.setText("");
        txtModifierArmor.setText("");
        txtStealthDArmor.setText("");
        txtStrenghtRArmor.setText("");
        txtTypeArmor.setText("");
        
        btnNewArmor.setEnabled(false);
        btnUpdateArmor.setEnabled(false);
        btnDeleteArmor.setEnabled(false);
        btnCancelArmor.setEnabled(true);
        btnSaveArmor.setEnabled(true);
        btnExitArmor.setEnabled(false);
    }//GEN-LAST:event_btnNewArmorMouseClicked

    private void btnUpdateArmorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateArmorMouseClicked
        // TODO add your handling code here:
        txtACBonus.setEnabled(true);
        txtModifierArmor.setEnabled(true);
        txtStealthDArmor.setEnabled(true);
        txtStrenghtRArmor.setEnabled(true);
        txtTypeArmor.setEnabled(true);
        
        btnNewArmor.setEnabled(false);
        btnUpdateArmor.setEnabled(false);
        btnDeleteArmor.setEnabled(false);
        btnCancelArmor.setEnabled(true);
        btnSaveArmor.setEnabled(true);
        btnExitArmor.setEnabled(false);
    }//GEN-LAST:event_btnUpdateArmorMouseClicked

    private void btnDeleteArmorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteArmorMouseClicked
        // TODO add your handling code here:
        txtACBonus.setEnabled(true);
        txtModifierArmor.setEnabled(true);
        txtStealthDArmor.setEnabled(true);
        txtStrenghtRArmor.setEnabled(true);
        txtTypeArmor.setEnabled(true);
        txtACBonus.setText("");
        txtModifierArmor.setText("");
        txtStealthDArmor.setText("");
        txtStrenghtRArmor.setText("");
        txtTypeArmor.setText("");
        
        btnNewArmor.setEnabled(false);
        btnUpdateArmor.setEnabled(false);
        btnDeleteArmor.setEnabled(false);
        btnCancelArmor.setEnabled(true);
        btnSaveArmor.setEnabled(true);
        btnExitArmor.setEnabled(false);
    }//GEN-LAST:event_btnDeleteArmorMouseClicked

    private void btnSaveArmorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSaveArmorMouseClicked
        // TODO add your handling code here:
        txtACBonus.setEnabled(false);
        txtModifierArmor.setEnabled(false);
        txtStealthDArmor.setEnabled(false);
        txtStrenghtRArmor.setEnabled(false);
        txtTypeArmor.setEnabled(false);
        txtACBonus.setText("");
        txtModifierArmor.setText("");
        txtStealthDArmor.setText("");
        txtStrenghtRArmor.setText("");
        txtTypeArmor.setText("");
        
        btnNewArmor.setEnabled(true);
        btnUpdateArmor.setEnabled(true);
        btnDeleteArmor.setEnabled(true);
        btnCancelArmor.setEnabled(false);
        btnSaveArmor.setEnabled(false);
        btnExitArmor.setEnabled(true);
    }//GEN-LAST:event_btnSaveArmorMouseClicked

    private void btnCancelArmorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelArmorMouseClicked
        // TODO add your handling code here:
        txtACBonus.setEnabled(false);
        txtModifierArmor.setEnabled(false);
        txtStealthDArmor.setEnabled(false);
        txtStrenghtRArmor.setEnabled(false);
        txtTypeArmor.setEnabled(false);
        txtACBonus.setText("");
        txtModifierArmor.setText("");
        txtStealthDArmor.setText("");
        txtStrenghtRArmor.setText("");
        txtTypeArmor.setText("");
        
        btnNewArmor.setEnabled(true);
        btnUpdateArmor.setEnabled(true);
        btnDeleteArmor.setEnabled(true);
        btnCancelArmor.setEnabled(false);
        btnSaveArmor.setEnabled(false);
        btnExitArmor.setEnabled(true);
    }//GEN-LAST:event_btnCancelArmorMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmVault.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmVault.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmVault.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmVault.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmVault().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnCancelArmor;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnDeleteArmor;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnExitArmor;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnNewArmor;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSaveArmor;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnUpdateArmor;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel jpAdventureGear;
    private javax.swing.JPanel jpArmor;
    private javax.swing.JPanel jpAttack;
    private javax.swing.JPanel jpAttribute;
    private javax.swing.JPanel jpEquipment;
    private javax.swing.JPanel jpItem;
    private javax.swing.JPanel jpMonster;
    private javax.swing.JPanel jpSpell;
    private javax.swing.JPanel jpVault;
    private javax.swing.JPanel jpWeapon;
    private javax.swing.JTabbedPane jtVault;
    private javax.swing.JLabel lblACBonus;
    private javax.swing.JLabel lblDescriptionGear;
    private javax.swing.JLabel lblModifierArmor;
    private javax.swing.JLabel lblStealthDArmor;
    private javax.swing.JLabel lblStrenghtRArmor;
    private javax.swing.JLabel lblTypeArmor;
    private javax.swing.JLabel lblTypeGear;
    private javax.swing.JToolBar tbAdventureGear;
    private javax.swing.JToolBar tbArmor;
    private javax.swing.JTable tblGear;
    private javax.swing.JTextField txtACBonus;
    private javax.swing.JTextArea txtDescription;
    private javax.swing.JTextField txtModifierArmor;
    private javax.swing.JTextField txtStealthDArmor;
    private javax.swing.JTextField txtStrenghtRArmor;
    private javax.swing.JTextField txtTypeArmor;
    private javax.swing.JTextField txtTypeGear;
    // End of variables declaration//GEN-END:variables
}
