/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

/**
 *
 * @author aluno
 */
public class frmVault extends javax.swing.JFrame {

    /**
     * Creates new form frmVault
     */
    public frmVault() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpVault = new javax.swing.JPanel();
        jtVault = new javax.swing.JTabbedPane();
        jpAdventureGear = new javax.swing.JPanel();
        lblDescriptionGear = new javax.swing.JLabel();
        lblTypeGear = new javax.swing.JLabel();
        txtTypeGear = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescription = new javax.swing.JTextArea();
        tbAdventureGear = new javax.swing.JToolBar();
        btnNew = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblGear = new javax.swing.JTable();
        jpArmor = new javax.swing.JPanel();
        lblTypeArmor = new javax.swing.JLabel();
        lblACBonus = new javax.swing.JLabel();
        lblModifierArmor = new javax.swing.JLabel();
        lblStealthDArmor = new javax.swing.JLabel();
        lblStrenghtRArmor = new javax.swing.JLabel();
        txtTypeArmor = new javax.swing.JTextField();
        txtACBonus = new javax.swing.JTextField();
        txtModifierArmor = new javax.swing.JTextField();
        txtStealthDArmor = new javax.swing.JTextField();
        txtStrenghtRArmor = new javax.swing.JTextField();
        tbArmor = new javax.swing.JToolBar();
        btnNewArmor = new javax.swing.JButton();
        btnUpdateArmor = new javax.swing.JButton();
        btnDeleteArmor = new javax.swing.JButton();
        btnSaveArmor = new javax.swing.JButton();
        btnCancelArmor = new javax.swing.JButton();
        btnExitArmor = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblArmor = new javax.swing.JTable();
        jpWeapon = new javax.swing.JPanel();
        lblAmmunitionWeapon = new javax.swing.JLabel();
        txtAmmunitionWeapon = new javax.swing.JTextField();
        txtFinesseWeapon = new javax.swing.JTextField();
        lblFinesseWeapon = new javax.swing.JLabel();
        txtLoadingWeapon = new javax.swing.JTextField();
        lblLoadWeapon = new javax.swing.JLabel();
        txtHeavyWeapon = new javax.swing.JTextField();
        lblHeavyWeapon = new javax.swing.JLabel();
        txtTypeWeapon = new javax.swing.JTextField();
        lblTypeWeapon = new javax.swing.JLabel();
        txtTwoHAttackWeapon = new javax.swing.JTextField();
        lblTwoHAttackWeapon = new javax.swing.JLabel();
        txtMinWeapon = new javax.swing.JTextField();
        lblMinWeapon = new javax.swing.JLabel();
        txtMaxWeapon = new javax.swing.JTextField();
        lblMaxWeapon = new javax.swing.JLabel();
        txtTwoHandedWeapon = new javax.swing.JTextField();
        lblTwoHandedWeapon = new javax.swing.JLabel();
        txtThrownWeapon = new javax.swing.JTextField();
        lblThrownWeapon = new javax.swing.JLabel();
        txtSConditionWeapon = new javax.swing.JTextField();
        lblSConditionWeapon = new javax.swing.JLabel();
        txtNAttackWeapon = new javax.swing.JTextField();
        lblNAttackWeapon = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblWeapon = new javax.swing.JTable();
        jToolBar1 = new javax.swing.JToolBar();
        btnNewWeapon = new javax.swing.JButton();
        btnUpdateWeapon = new javax.swing.JButton();
        btnDeleteWeapon = new javax.swing.JButton();
        btnSaveWeapon = new javax.swing.JButton();
        btnCancelWeapon = new javax.swing.JButton();
        btnExitWeapon = new javax.swing.JButton();
        jpMonster = new javax.swing.JPanel();
        lblActionsMonster = new javax.swing.JLabel();
        lblLActions = new javax.swing.JLabel();
        lblReactionsMonster = new javax.swing.JLabel();
        lblSTraitsMonster = new javax.swing.JLabel();
        lblChallengeMonster = new javax.swing.JLabel();
        lblACTypeMonster = new javax.swing.JLabel();
        lblACMonster = new javax.swing.JLabel();
        lblAlignment = new javax.swing.JLabel();
        lblTypeMonster = new javax.swing.JLabel();
        lblSyzeMonster = new javax.swing.JLabel();
        lblNameMonster = new javax.swing.JLabel();
        lblDescriptionMonster = new javax.swing.JLabel();
        txtAlignmentMonster = new javax.swing.JTextField();
        txtACMonster = new javax.swing.JTextField();
        txtACTypeMonster = new javax.swing.JTextField();
        txtChallengeMonster = new javax.swing.JTextField();
        txtNameMonster = new javax.swing.JTextField();
        txtSyzeMonster = new javax.swing.JTextField();
        txtTypeMonster = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtDescriptionMonster = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        tblMonster = new javax.swing.JTable();
        tbMonster = new javax.swing.JToolBar();
        btnNewMonster = new javax.swing.JButton();
        btnUpdateMonster = new javax.swing.JButton();
        btnDeleteMonster = new javax.swing.JButton();
        btnSaveMonster = new javax.swing.JButton();
        btnCancelMonster = new javax.swing.JButton();
        btnExitMonster = new javax.swing.JButton();
        jpRace = new javax.swing.JPanel();
        lblAttackBRace = new javax.swing.JLabel();
        lblLanguageRace = new javax.swing.JLabel();
        lblLoreTraitRace = new javax.swing.JLabel();
        lblTraitRace = new javax.swing.JLabel();
        lblSpeedRace = new javax.swing.JLabel();
        lblNameRace = new javax.swing.JLabel();
        txtAttackBRace = new javax.swing.JTextField();
        txtLanguageRace = new javax.swing.JTextField();
        txtNameRace = new javax.swing.JTextField();
        txtSpeedRace = new javax.swing.JTextField();
        jScrollPane7 = new javax.swing.JScrollPane();
        tblRace = new javax.swing.JTable();
        jToolBar2 = new javax.swing.JToolBar();
        btnNewRace = new javax.swing.JButton();
        btnUpdateRace = new javax.swing.JButton();
        btnDeleteRace = new javax.swing.JButton();
        btnSaveRace = new javax.swing.JButton();
        btnCancelRace = new javax.swing.JButton();
        btnExitRace = new javax.swing.JButton();
        jpClass = new javax.swing.JPanel();
        jpSpell = new javax.swing.JPanel();
        jpAttribute = new javax.swing.JPanel();
        jpItem = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Vault");
        setName("jfVault"); // NOI18N

        jpAdventureGear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpAdventureGearMouseClicked(evt);
            }
        });
        jpAdventureGear.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jpAdventureGearComponentShown(evt);
            }
        });

        lblDescriptionGear.setText("Description :");

        lblTypeGear.setText("Gear Type :");

        txtDescription.setColumns(20);
        txtDescription.setRows(5);
        jScrollPane1.setViewportView(txtDescription);

        tbAdventureGear.setRollover(true);

        btnNew.setText("New");
        btnNew.setFocusable(false);
        btnNew.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNew.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNew.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNewMouseClicked(evt);
            }
        });
        tbAdventureGear.add(btnNew);

        btnUpdate.setText("Update");
        btnUpdate.setFocusable(false);
        btnUpdate.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnUpdate.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUpdateMouseClicked(evt);
            }
        });
        tbAdventureGear.add(btnUpdate);

        btnDelete.setText("Delete");
        btnDelete.setFocusable(false);
        btnDelete.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDelete.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDeleteMouseClicked(evt);
            }
        });
        tbAdventureGear.add(btnDelete);

        btnSave.setText("Save");
        btnSave.setFocusable(false);
        btnSave.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSave.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSaveMouseClicked(evt);
            }
        });
        tbAdventureGear.add(btnSave);

        btnCancel.setText("Cancel");
        btnCancel.setFocusable(false);
        btnCancel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCancel.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelMouseClicked(evt);
            }
        });
        tbAdventureGear.add(btnCancel);

        btnExit.setText("Exit");
        btnExit.setFocusable(false);
        btnExit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnExit.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tbAdventureGear.add(btnExit);

        tblGear.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblGear);

        javax.swing.GroupLayout jpAdventureGearLayout = new javax.swing.GroupLayout(jpAdventureGear);
        jpAdventureGear.setLayout(jpAdventureGearLayout);
        jpAdventureGearLayout.setHorizontalGroup(
            jpAdventureGearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpAdventureGearLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jpAdventureGearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDescriptionGear)
                    .addComponent(txtTypeGear, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTypeGear)
                    .addComponent(tbAdventureGear, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(384, Short.MAX_VALUE))
        );
        jpAdventureGearLayout.setVerticalGroup(
            jpAdventureGearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpAdventureGearLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jpAdventureGearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jpAdventureGearLayout.createSequentialGroup()
                        .addComponent(lblDescriptionGear)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(lblTypeGear)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTypeGear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(76, 76, 76)
                        .addComponent(tbAdventureGear, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(404, Short.MAX_VALUE))
        );

        jtVault.addTab("Adventure Gear", jpAdventureGear);

        jpArmor.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jpArmorComponentShown(evt);
            }
        });

        lblTypeArmor.setText("Armor Type :");

        lblACBonus.setText("AC Bonus Base :");

        lblModifierArmor.setText("Modifier :");

        lblStealthDArmor.setText("Stealth Disadvantage :");

        lblStrenghtRArmor.setText("Strenght Requirement :");

        tbArmor.setRollover(true);

        btnNewArmor.setText("New");
        btnNewArmor.setFocusable(false);
        btnNewArmor.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNewArmor.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNewArmor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNewArmorMouseClicked(evt);
            }
        });
        tbArmor.add(btnNewArmor);

        btnUpdateArmor.setText("Update");
        btnUpdateArmor.setFocusable(false);
        btnUpdateArmor.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnUpdateArmor.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnUpdateArmor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUpdateArmorMouseClicked(evt);
            }
        });
        tbArmor.add(btnUpdateArmor);

        btnDeleteArmor.setText("Delete");
        btnDeleteArmor.setFocusable(false);
        btnDeleteArmor.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDeleteArmor.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDeleteArmor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDeleteArmorMouseClicked(evt);
            }
        });
        tbArmor.add(btnDeleteArmor);

        btnSaveArmor.setText("Save");
        btnSaveArmor.setFocusable(false);
        btnSaveArmor.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSaveArmor.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSaveArmor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSaveArmorMouseClicked(evt);
            }
        });
        tbArmor.add(btnSaveArmor);

        btnCancelArmor.setText("Cancel");
        btnCancelArmor.setFocusable(false);
        btnCancelArmor.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCancelArmor.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCancelArmor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelArmorMouseClicked(evt);
            }
        });
        tbArmor.add(btnCancelArmor);

        btnExitArmor.setText("Exit");
        btnExitArmor.setFocusable(false);
        btnExitArmor.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnExitArmor.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tbArmor.add(btnExitArmor);

        tblArmor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tblArmor);

        javax.swing.GroupLayout jpArmorLayout = new javax.swing.GroupLayout(jpArmor);
        jpArmor.setLayout(jpArmorLayout);
        jpArmorLayout.setHorizontalGroup(
            jpArmorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpArmorLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jpArmorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpArmorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblStrenghtRArmor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblModifierArmor)
                        .addComponent(lblACBonus)
                        .addComponent(lblTypeArmor)
                        .addComponent(txtStealthDArmor)
                        .addComponent(lblStealthDArmor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtModifierArmor)
                        .addComponent(txtStrenghtRArmor))
                    .addGroup(jpArmorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtTypeArmor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                        .addComponent(txtACBonus, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(tbArmor, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(430, Short.MAX_VALUE))
        );
        jpArmorLayout.setVerticalGroup(
            jpArmorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpArmorLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jpArmorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpArmorLayout.createSequentialGroup()
                        .addComponent(lblTypeArmor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTypeArmor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblACBonus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtACBonus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblModifierArmor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtModifierArmor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblStealthDArmor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtStealthDArmor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblStrenghtRArmor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtStrenghtRArmor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tbArmor, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(337, Short.MAX_VALUE))
        );

        jtVault.addTab("Armor", jpArmor);

        jpWeapon.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jpWeaponComponentShown(evt);
            }
        });

        lblAmmunitionWeapon.setText("Ammunition :");

        lblFinesseWeapon.setText("Finesse :");

        lblLoadWeapon.setText("Loading :");

        lblHeavyWeapon.setText("Heavy :");

        lblTypeWeapon.setText("Weapon Type :");

        lblTwoHAttackWeapon.setText("Two Handed Attack :");

        lblMinWeapon.setText("Min Range :");

        lblMaxWeapon.setText("Max Range :");

        lblTwoHandedWeapon.setText("Two Handed :");

        lblThrownWeapon.setText("Thrown :");

        lblSConditionWeapon.setText("Special Condition :");

        lblNAttackWeapon.setText("Normal Attack :");

        tblWeapon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(tblWeapon);

        jToolBar1.setRollover(true);

        btnNewWeapon.setText("New");
        btnNewWeapon.setFocusable(false);
        btnNewWeapon.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNewWeapon.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNewWeapon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNewWeaponMouseClicked(evt);
            }
        });
        jToolBar1.add(btnNewWeapon);

        btnUpdateWeapon.setText("Update");
        btnUpdateWeapon.setFocusable(false);
        btnUpdateWeapon.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnUpdateWeapon.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnUpdateWeapon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUpdateWeaponMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnUpdateWeaponMouseEntered(evt);
            }
        });
        jToolBar1.add(btnUpdateWeapon);

        btnDeleteWeapon.setText("Delete");
        btnDeleteWeapon.setFocusable(false);
        btnDeleteWeapon.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDeleteWeapon.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnDeleteWeapon);

        btnSaveWeapon.setText("Save");
        btnSaveWeapon.setFocusable(false);
        btnSaveWeapon.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSaveWeapon.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSaveWeapon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSaveWeaponMouseClicked(evt);
            }
        });
        jToolBar1.add(btnSaveWeapon);

        btnCancelWeapon.setText("Cancel");
        btnCancelWeapon.setFocusable(false);
        btnCancelWeapon.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCancelWeapon.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCancelWeapon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelWeaponMouseClicked(evt);
            }
        });
        jToolBar1.add(btnCancelWeapon);

        btnExitWeapon.setText("Exit");
        btnExitWeapon.setFocusable(false);
        btnExitWeapon.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnExitWeapon.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnExitWeapon);

        javax.swing.GroupLayout jpWeaponLayout = new javax.swing.GroupLayout(jpWeapon);
        jpWeapon.setLayout(jpWeaponLayout);
        jpWeaponLayout.setHorizontalGroup(
            jpWeaponLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpWeaponLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpWeaponLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpWeaponLayout.createSequentialGroup()
                        .addGroup(jpWeaponLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblAmmunitionWeapon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblFinesseWeapon)
                            .addComponent(lblHeavyWeapon)
                            .addComponent(lblLoadWeapon)
                            .addComponent(lblMinWeapon)
                            .addComponent(txtFinesseWeapon)
                            .addComponent(txtHeavyWeapon)
                            .addComponent(txtMinWeapon)
                            .addComponent(lblMaxWeapon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtMaxWeapon)
                            .addComponent(txtLoadingWeapon)
                            .addComponent(txtAmmunitionWeapon))
                        .addGap(64, 64, 64)
                        .addGroup(jpWeaponLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblTwoHAttackWeapon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblTypeWeapon)
                            .addComponent(lblNAttackWeapon)
                            .addComponent(lblSConditionWeapon)
                            .addComponent(lblThrownWeapon)
                            .addComponent(lblTwoHandedWeapon)
                            .addComponent(txtNAttackWeapon)
                            .addComponent(txtSConditionWeapon)
                            .addComponent(txtThrownWeapon)
                            .addComponent(txtTwoHandedWeapon)
                            .addComponent(txtTwoHAttackWeapon)
                            .addComponent(txtTypeWeapon)))
                    .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(402, Short.MAX_VALUE))
        );
        jpWeaponLayout.setVerticalGroup(
            jpWeaponLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpWeaponLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpWeaponLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpWeaponLayout.createSequentialGroup()
                        .addGroup(jpWeaponLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpWeaponLayout.createSequentialGroup()
                                .addComponent(lblAmmunitionWeapon)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtAmmunitionWeapon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblFinesseWeapon)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtFinesseWeapon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblHeavyWeapon)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtHeavyWeapon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblLoadWeapon)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtLoadingWeapon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpWeaponLayout.createSequentialGroup()
                                .addComponent(lblNAttackWeapon)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNAttackWeapon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblSConditionWeapon)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtSConditionWeapon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblThrownWeapon)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtThrownWeapon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblTwoHandedWeapon)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTwoHandedWeapon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jpWeaponLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpWeaponLayout.createSequentialGroup()
                                .addComponent(lblMaxWeapon)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtMaxWeapon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblMinWeapon)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtMinWeapon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpWeaponLayout.createSequentialGroup()
                                .addComponent(lblTwoHAttackWeapon)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTwoHAttackWeapon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblTypeWeapon)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTypeWeapon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(59, 59, 59)
                        .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(360, Short.MAX_VALUE))
        );

        jtVault.addTab("Weapon", jpWeapon);

        jpMonster.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jpMonsterComponentShown(evt);
            }
        });

        lblActionsMonster.setText("Actions :");

        lblLActions.setText("Legendary Actions :");

        lblReactionsMonster.setText("Reactions :");

        lblSTraitsMonster.setText("Special Traits :");

        lblChallengeMonster.setText("Challenge Rating :");

        lblACTypeMonster.setText("Armor Class Type: ");

        lblACMonster.setText("Armor Class :");

        lblAlignment.setText("Alignment :");

        lblTypeMonster.setText("Type :");

        lblSyzeMonster.setText("Syze :");

        lblNameMonster.setText("Name :");

        lblDescriptionMonster.setText("Description :");

        txtACMonster.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtACMonsterActionPerformed(evt);
            }
        });

        txtChallengeMonster.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtChallengeMonsterActionPerformed(evt);
            }
        });

        txtNameMonster.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameMonsterActionPerformed(evt);
            }
        });

        txtDescriptionMonster.setColumns(20);
        txtDescriptionMonster.setRows(5);
        jScrollPane5.setViewportView(txtDescriptionMonster);

        tblMonster.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane6.setViewportView(tblMonster);

        tbMonster.setRollover(true);

        btnNewMonster.setText("New");
        btnNewMonster.setFocusable(false);
        btnNewMonster.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNewMonster.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNewMonster.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNewMonsterMouseClicked(evt);
            }
        });
        tbMonster.add(btnNewMonster);

        btnUpdateMonster.setText("Update");
        btnUpdateMonster.setFocusable(false);
        btnUpdateMonster.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnUpdateMonster.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnUpdateMonster.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUpdateMonsterMouseClicked(evt);
            }
        });
        tbMonster.add(btnUpdateMonster);

        btnDeleteMonster.setText("Delete");
        btnDeleteMonster.setFocusable(false);
        btnDeleteMonster.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDeleteMonster.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDeleteMonster.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDeleteMonsterMouseClicked(evt);
            }
        });
        tbMonster.add(btnDeleteMonster);

        btnSaveMonster.setText("Save");
        btnSaveMonster.setFocusable(false);
        btnSaveMonster.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSaveMonster.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSaveMonster.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSaveMonsterMouseClicked(evt);
            }
        });
        tbMonster.add(btnSaveMonster);

        btnCancelMonster.setText("Cancel");
        btnCancelMonster.setFocusable(false);
        btnCancelMonster.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCancelMonster.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCancelMonster.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelMonsterMouseClicked(evt);
            }
        });
        tbMonster.add(btnCancelMonster);

        btnExitMonster.setText("Exit");
        btnExitMonster.setFocusable(false);
        btnExitMonster.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnExitMonster.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tbMonster.add(btnExitMonster);

        javax.swing.GroupLayout jpMonsterLayout = new javax.swing.GroupLayout(jpMonster);
        jpMonster.setLayout(jpMonsterLayout);
        jpMonsterLayout.setHorizontalGroup(
            jpMonsterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMonsterLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpMonsterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtACTypeMonster, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblChallengeMonster)
                    .addGroup(jpMonsterLayout.createSequentialGroup()
                        .addGroup(jpMonsterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpMonsterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(lblAlignment, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblACMonster, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtAlignmentMonster, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                                .addComponent(txtACMonster, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(lblACTypeMonster)
                            .addComponent(lblSyzeMonster)
                            .addComponent(lblTypeMonster)
                            .addGroup(jpMonsterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtTypeMonster, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                                .addComponent(txtSyzeMonster, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtNameMonster)
                                .addComponent(txtChallengeMonster))
                            .addComponent(lblNameMonster))
                        .addGap(127, 127, 127)
                        .addGroup(jpMonsterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDescriptionMonster)
                            .addComponent(lblLActions)
                            .addComponent(lblActionsMonster)
                            .addComponent(lblReactionsMonster)
                            .addComponent(lblSTraitsMonster)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(tbMonster, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 279, Short.MAX_VALUE)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
        );
        jpMonsterLayout.setVerticalGroup(
            jpMonsterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMonsterLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jpMonsterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jpMonsterLayout.createSequentialGroup()
                        .addGroup(jpMonsterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpMonsterLayout.createSequentialGroup()
                                .addComponent(lblActionsMonster)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblLActions)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jpMonsterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblACMonster, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblReactionsMonster)))
                            .addGroup(jpMonsterLayout.createSequentialGroup()
                                .addComponent(lblAlignment)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtAlignmentMonster, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpMonsterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblSTraitsMonster)
                            .addComponent(txtACMonster, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblACTypeMonster)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtACTypeMonster, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblChallengeMonster)
                        .addGap(5, 5, 5)
                        .addComponent(txtChallengeMonster, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addGroup(jpMonsterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNameMonster)
                            .addComponent(lblDescriptionMonster))
                        .addGap(4, 4, 4)
                        .addGroup(jpMonsterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpMonsterLayout.createSequentialGroup()
                                .addComponent(txtNameMonster, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblSyzeMonster)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtSyzeMonster, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblTypeMonster)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTypeMonster, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tbMonster, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpMonsterLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(327, Short.MAX_VALUE))
        );

        jtVault.addTab("Monster", jpMonster);

        jpRace.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jpRaceComponentShown(evt);
            }
        });

        lblAttackBRace.setText("Attack Bonus :");

        lblLanguageRace.setText("Languages :");

        lblLoreTraitRace.setText("Lore Traits :");

        lblTraitRace.setText("Traits :");

        lblSpeedRace.setText("Speed :");

        lblNameRace.setText("Name :");

        txtAttackBRace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAttackBRaceActionPerformed(evt);
            }
        });

        tblRace.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane7.setViewportView(tblRace);

        jToolBar2.setRollover(true);

        btnNewRace.setText("New");
        btnNewRace.setFocusable(false);
        btnNewRace.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNewRace.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNewRace.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNewRaceMouseClicked(evt);
            }
        });
        jToolBar2.add(btnNewRace);

        btnUpdateRace.setText("Update");
        btnUpdateRace.setFocusable(false);
        btnUpdateRace.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnUpdateRace.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnUpdateRace.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUpdateRaceMouseClicked(evt);
            }
        });
        jToolBar2.add(btnUpdateRace);

        btnDeleteRace.setText("Delete");
        btnDeleteRace.setFocusable(false);
        btnDeleteRace.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDeleteRace.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDeleteRace.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDeleteRaceMouseClicked(evt);
            }
        });
        jToolBar2.add(btnDeleteRace);

        btnSaveRace.setText("Save");
        btnSaveRace.setFocusable(false);
        btnSaveRace.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSaveRace.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSaveRace.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSaveRaceMouseClicked(evt);
            }
        });
        jToolBar2.add(btnSaveRace);

        btnCancelRace.setText("Cancel");
        btnCancelRace.setFocusable(false);
        btnCancelRace.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCancelRace.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCancelRace.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelRaceMouseClicked(evt);
            }
        });
        jToolBar2.add(btnCancelRace);

        btnExitRace.setText("Exit");
        btnExitRace.setFocusable(false);
        btnExitRace.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnExitRace.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar2.add(btnExitRace);

        javax.swing.GroupLayout jpRaceLayout = new javax.swing.GroupLayout(jpRace);
        jpRace.setLayout(jpRaceLayout);
        jpRaceLayout.setHorizontalGroup(
            jpRaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpRaceLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpRaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpRaceLayout.createSequentialGroup()
                        .addGroup(jpRaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblAttackBRace)
                            .addComponent(lblLanguageRace)
                            .addComponent(txtAttackBRace)
                            .addComponent(txtLanguageRace)
                            .addComponent(lblNameRace)
                            .addComponent(lblSpeedRace)
                            .addComponent(txtNameRace)
                            .addComponent(txtSpeedRace, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                        .addGap(89, 89, 89)
                        .addGroup(jpRaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblLoreTraitRace)
                            .addComponent(lblTraitRace)))
                    .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 213, Short.MAX_VALUE)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(215, 215, 215))
        );
        jpRaceLayout.setVerticalGroup(
            jpRaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpRaceLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpRaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpRaceLayout.createSequentialGroup()
                        .addGroup(jpRaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblLoreTraitRace)
                            .addGroup(jpRaceLayout.createSequentialGroup()
                                .addComponent(lblAttackBRace)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtAttackBRace, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15)
                                .addComponent(lblLanguageRace)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtLanguageRace, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(lblNameRace)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpRaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNameRace, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTraitRace))
                        .addGap(18, 18, 18)
                        .addComponent(lblSpeedRace)
                        .addGap(7, 7, 7)
                        .addComponent(txtSpeedRace, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(360, Short.MAX_VALUE))
        );

        jtVault.addTab("Race", jpRace);

        javax.swing.GroupLayout jpClassLayout = new javax.swing.GroupLayout(jpClass);
        jpClass.setLayout(jpClassLayout);
        jpClassLayout.setHorizontalGroup(
            jpClassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1221, Short.MAX_VALUE)
        );
        jpClassLayout.setVerticalGroup(
            jpClassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 798, Short.MAX_VALUE)
        );

        jtVault.addTab("Class", jpClass);

        javax.swing.GroupLayout jpSpellLayout = new javax.swing.GroupLayout(jpSpell);
        jpSpell.setLayout(jpSpellLayout);
        jpSpellLayout.setHorizontalGroup(
            jpSpellLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1221, Short.MAX_VALUE)
        );
        jpSpellLayout.setVerticalGroup(
            jpSpellLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 798, Short.MAX_VALUE)
        );

        jtVault.addTab("Spell", jpSpell);

        javax.swing.GroupLayout jpAttributeLayout = new javax.swing.GroupLayout(jpAttribute);
        jpAttribute.setLayout(jpAttributeLayout);
        jpAttributeLayout.setHorizontalGroup(
            jpAttributeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1221, Short.MAX_VALUE)
        );
        jpAttributeLayout.setVerticalGroup(
            jpAttributeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 798, Short.MAX_VALUE)
        );

        jtVault.addTab("Attribute", jpAttribute);

        javax.swing.GroupLayout jpItemLayout = new javax.swing.GroupLayout(jpItem);
        jpItem.setLayout(jpItemLayout);
        jpItemLayout.setHorizontalGroup(
            jpItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1221, Short.MAX_VALUE)
        );
        jpItemLayout.setVerticalGroup(
            jpItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 798, Short.MAX_VALUE)
        );

        jtVault.addTab("Item", jpItem);

        javax.swing.GroupLayout jpVaultLayout = new javax.swing.GroupLayout(jpVault);
        jpVault.setLayout(jpVaultLayout);
        jpVaultLayout.setHorizontalGroup(
            jpVaultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1229, Short.MAX_VALUE)
            .addGroup(jpVaultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jpVaultLayout.createSequentialGroup()
                    .addGap(1, 1, 1)
                    .addComponent(jtVault)
                    .addGap(2, 2, 2)))
        );
        jpVaultLayout.setVerticalGroup(
            jpVaultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 848, Short.MAX_VALUE)
            .addGroup(jpVaultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jpVaultLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jtVault)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpVault, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpVault, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jpAdventureGearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpAdventureGearMouseClicked
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jpAdventureGearMouseClicked

    private void jpAdventureGearComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jpAdventureGearComponentShown
        // TODO add your handling code here:
         //Desabilitando as caixas de edição
        txtDescription.setEnabled(false);
        txtTypeGear.setEnabled(false);
        
        //Habilitando a barra de ferramentas
        btnNew.setEnabled(true);
        btnUpdate.setEnabled(true);
        btnDelete.setEnabled(true);
        btnCancel.setEnabled(false);
        btnSave.setEnabled(false);
        btnExit.setEnabled(true);
    }//GEN-LAST:event_jpAdventureGearComponentShown

    private void btnNewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNewMouseClicked
        // TODO add your handling code here:
        txtDescription.setEnabled(true);
        txtTypeGear.setEnabled(true);
        txtDescription.setText("");
        txtTypeGear.setText("");
        
        btnNew.setEnabled(false);
        btnUpdate.setEnabled(false);
        btnDelete.setEnabled(false);
        btnCancel.setEnabled(true);
        btnSave.setEnabled(true);
        btnExit.setEnabled(false);
    }//GEN-LAST:event_btnNewMouseClicked

    private void btnUpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateMouseClicked
        // TODO add your handling code here:
        txtDescription.setEnabled(true);
        txtTypeGear.setEnabled(true);
        
        btnNew.setEnabled(false);
        btnUpdate.setEnabled(false);
        btnDelete.setEnabled(false);
        btnCancel.setEnabled(true);
        btnSave.setEnabled(true);
        btnExit.setEnabled(false);
    }//GEN-LAST:event_btnUpdateMouseClicked

    private void btnDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteMouseClicked
        // TODO add your handling code here:
      /*  txtDescription.setEnabled(true);
        txtTypeGear.setEnabled(true);
        txtDescription.setText("");
        txtTypeGear.setText("");
        
        btnNew.setEnabled(false);
        btnUpdate.setEnabled(false);
        btnDelete.setEnabled(false);
        btnCancel.setEnabled(true);
        btnSave.setEnabled(true);
        btnExit.setEnabled(false);
        */
    }//GEN-LAST:event_btnDeleteMouseClicked

    private void btnSaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSaveMouseClicked
        // TODO add your handling code here:
        txtDescription.setEnabled(false);
        txtTypeGear.setEnabled(false);
        txtDescription.setText("");
        txtTypeGear.setText("");
        
        btnNew.setEnabled(true);
        btnUpdate.setEnabled(true);
        btnDelete.setEnabled(true);
        btnCancel.setEnabled(false);
        btnSave.setEnabled(false);
        btnExit.setEnabled(true);
    }//GEN-LAST:event_btnSaveMouseClicked

    private void btnCancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelMouseClicked
        // TODO add your handling code here:
        txtDescription.setEnabled(false);
        txtTypeGear.setEnabled(false);
        txtDescription.setText("");
        txtTypeGear.setText("");
        //Habilitando a barra de ferramentas
        btnNew.setEnabled(true);
        btnUpdate.setEnabled(true);
        btnDelete.setEnabled(true);
        btnCancel.setEnabled(false);
        btnSave.setEnabled(false);
        btnExit.setEnabled(true);
    }//GEN-LAST:event_btnCancelMouseClicked

    private void jpArmorComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jpArmorComponentShown
        // TODO add your handling code here:
        txtTypeArmor.setEnabled(false);
        txtACBonus.setEnabled(false);
        txtModifierArmor.setEnabled(false);
        txtStealthDArmor.setEnabled(false);
        txtStrenghtRArmor.setEnabled(false);
        
        btnNewArmor.setEnabled(true);
        btnUpdateArmor.setEnabled(true);
        btnDeleteArmor.setEnabled(true);
        btnCancelArmor.setEnabled(false);
        btnSaveArmor.setEnabled(false);
        btnExitArmor.setEnabled(true);
    }//GEN-LAST:event_jpArmorComponentShown

    private void btnNewArmorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNewArmorMouseClicked
        // TODO add your handling code here:
        txtACBonus.setEnabled(true);
        txtModifierArmor.setEnabled(true);
        txtStealthDArmor.setEnabled(true);
        txtStrenghtRArmor.setEnabled(true);
        txtTypeArmor.setEnabled(true);
        txtACBonus.setText("");
        txtModifierArmor.setText("");
        txtStealthDArmor.setText("");
        txtStrenghtRArmor.setText("");
        txtTypeArmor.setText("");
        
        btnNewArmor.setEnabled(false);
        btnUpdateArmor.setEnabled(false);
        btnDeleteArmor.setEnabled(false);
        btnCancelArmor.setEnabled(true);
        btnSaveArmor.setEnabled(true);
        btnExitArmor.setEnabled(false);
    }//GEN-LAST:event_btnNewArmorMouseClicked

    private void btnUpdateArmorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateArmorMouseClicked
        // TODO add your handling code here:
        txtACBonus.setEnabled(true);
        txtModifierArmor.setEnabled(true);
        txtStealthDArmor.setEnabled(true);
        txtStrenghtRArmor.setEnabled(true);
        txtTypeArmor.setEnabled(true);
        
        btnNewArmor.setEnabled(false);
        btnUpdateArmor.setEnabled(false);
        btnDeleteArmor.setEnabled(false);
        btnCancelArmor.setEnabled(true);
        btnSaveArmor.setEnabled(true);
        btnExitArmor.setEnabled(false);
    }//GEN-LAST:event_btnUpdateArmorMouseClicked

    private void btnDeleteArmorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteArmorMouseClicked
        // TODO add your handling code here:
        /*txtACBonus.setEnabled(true);
        txtModifierArmor.setEnabled(true);
        txtStealthDArmor.setEnabled(true);
        txtStrenghtRArmor.setEnabled(true);
        txtTypeArmor.setEnabled(true);
        txtACBonus.setText("");
        txtModifierArmor.setText("");
        txtStealthDArmor.setText("");
        txtStrenghtRArmor.setText("");
        txtTypeArmor.setText("");
        
        btnNewArmor.setEnabled(false);
        btnUpdateArmor.setEnabled(false);
        btnDeleteArmor.setEnabled(false);
        btnCancelArmor.setEnabled(true);
        btnSaveArmor.setEnabled(true);
        btnExitArmor.setEnabled(false);
        */
    }//GEN-LAST:event_btnDeleteArmorMouseClicked

    private void btnSaveArmorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSaveArmorMouseClicked
        // TODO add your handling code here:
        txtACBonus.setEnabled(false);
        txtModifierArmor.setEnabled(false);
        txtStealthDArmor.setEnabled(false);
        txtStrenghtRArmor.setEnabled(false);
        txtTypeArmor.setEnabled(false);
        txtACBonus.setText("");
        txtModifierArmor.setText("");
        txtStealthDArmor.setText("");
        txtStrenghtRArmor.setText("");
        txtTypeArmor.setText("");
        
        btnNewArmor.setEnabled(true);
        btnUpdateArmor.setEnabled(true);
        btnDeleteArmor.setEnabled(true);
        btnCancelArmor.setEnabled(false);
        btnSaveArmor.setEnabled(false);
        btnExitArmor.setEnabled(true);
    }//GEN-LAST:event_btnSaveArmorMouseClicked

    private void btnCancelArmorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelArmorMouseClicked
        // TODO add your handling code here:
        txtACBonus.setEnabled(false);
        txtModifierArmor.setEnabled(false);
        txtStealthDArmor.setEnabled(false);
        txtStrenghtRArmor.setEnabled(false);
        txtTypeArmor.setEnabled(false);
        txtACBonus.setText("");
        txtModifierArmor.setText("");
        txtStealthDArmor.setText("");
        txtStrenghtRArmor.setText("");
        txtTypeArmor.setText("");
        
        btnNewArmor.setEnabled(true);
        btnUpdateArmor.setEnabled(true);
        btnDeleteArmor.setEnabled(true);
        btnCancelArmor.setEnabled(false);
        btnSaveArmor.setEnabled(false);
        btnExitArmor.setEnabled(true);
    }//GEN-LAST:event_btnCancelArmorMouseClicked

    private void btnNewWeaponMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNewWeaponMouseClicked
        // TODO add your handling code here:
        txtAmmunitionWeapon.setEnabled(true);
        txtFinesseWeapon.setEnabled(true);
        txtHeavyWeapon.setEnabled(true);
        txtLoadingWeapon.setEnabled(true);
        txtMaxWeapon.setEnabled(true);
        txtMinWeapon.setEnabled(true);
        txtTypeWeapon.setEnabled(true);
        txtNAttackWeapon.setEnabled(true);
        txtSConditionWeapon.setEnabled(true);
        txtThrownWeapon.setEnabled(true);
        txtTwoHAttackWeapon.setEnabled(true);
        txtTwoHandedWeapon.setEnabled(true);
        txtTypeWeapon.setText("");
        txtAmmunitionWeapon.setText("");
        txtFinesseWeapon.setText("");
        txtHeavyWeapon.setText("");
        txtLoadingWeapon.setText("");
        txtMaxWeapon.setText("");
        txtMinWeapon.setText("");
        txtNAttackWeapon.setText("");
        txtSConditionWeapon.setText("");
        txtThrownWeapon.setText("");
        txtTwoHAttackWeapon.setText("");
        txtTwoHandedWeapon.setText("");
        
        btnNewWeapon.setEnabled(false);
        btnUpdateWeapon.setEnabled(false);
        btnDeleteWeapon.setEnabled(false);
        btnCancelWeapon.setEnabled(true);
        btnSaveWeapon.setEnabled(true);
        btnExitWeapon.setEnabled(false);
    }//GEN-LAST:event_btnNewWeaponMouseClicked

    private void btnUpdateWeaponMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateWeaponMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdateWeaponMouseEntered

    private void btnUpdateWeaponMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateWeaponMouseClicked
        // TODO add your handling code here:
        txtAmmunitionWeapon.setEnabled(true);
        txtFinesseWeapon.setEnabled(true);
        txtHeavyWeapon.setEnabled(true);
        txtLoadingWeapon.setEnabled(true);
        txtMaxWeapon.setEnabled(true);
        txtMinWeapon.setEnabled(true);
        txtTypeWeapon.setEnabled(true);
        txtNAttackWeapon.setEnabled(true);
        txtSConditionWeapon.setEnabled(true);
        txtThrownWeapon.setEnabled(true);
        txtTwoHAttackWeapon.setEnabled(true);
        txtTwoHandedWeapon.setEnabled(true);
        
        btnNewWeapon.setEnabled(false);
        btnUpdateWeapon.setEnabled(false);
        btnDeleteWeapon.setEnabled(false);
        btnCancelWeapon.setEnabled(true);
        btnSaveWeapon.setEnabled(true);
        btnExitWeapon.setEnabled(false);
    }//GEN-LAST:event_btnUpdateWeaponMouseClicked

    private void btnSaveWeaponMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSaveWeaponMouseClicked
        // TODO add your handling code here:
        txtAmmunitionWeapon.setEnabled(false);
        txtFinesseWeapon.setEnabled(false);
        txtHeavyWeapon.setEnabled(false);
        txtLoadingWeapon.setEnabled(false);
        txtMaxWeapon.setEnabled(false);
        txtMinWeapon.setEnabled(false);
        txtTypeWeapon.setEnabled(false);
        txtNAttackWeapon.setEnabled(false);
        txtSConditionWeapon.setEnabled(false);
        txtThrownWeapon.setEnabled(false);
        txtTwoHAttackWeapon.setEnabled(false);
        txtTwoHandedWeapon.setEnabled(false);
        txtTypeWeapon.setText("");
        txtAmmunitionWeapon.setText("");
        txtFinesseWeapon.setText("");
        txtHeavyWeapon.setText("");
        txtLoadingWeapon.setText("");
        txtMaxWeapon.setText("");
        txtMinWeapon.setText("");
        txtNAttackWeapon.setText("");
        txtSConditionWeapon.setText("");
        txtThrownWeapon.setText("");
        txtTwoHAttackWeapon.setText("");
        txtTwoHandedWeapon.setText("");
        
        btnNewWeapon.setEnabled(true);
        btnUpdateWeapon.setEnabled(true);
        btnDeleteWeapon.setEnabled(true);
        btnCancelWeapon.setEnabled(false);
        btnSaveWeapon.setEnabled(false);
        btnExitWeapon.setEnabled(true);
    }//GEN-LAST:event_btnSaveWeaponMouseClicked

    private void btnCancelWeaponMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelWeaponMouseClicked
        // TODO add your handling code here:
        txtAmmunitionWeapon.setEnabled(false);
        txtFinesseWeapon.setEnabled(false);
        txtHeavyWeapon.setEnabled(false);
        txtLoadingWeapon.setEnabled(false);
        txtMaxWeapon.setEnabled(false);
        txtMinWeapon.setEnabled(false);
        txtTypeWeapon.setEnabled(false);
        txtNAttackWeapon.setEnabled(false);
        txtSConditionWeapon.setEnabled(false);
        txtThrownWeapon.setEnabled(false);
        txtTwoHAttackWeapon.setEnabled(false);
        txtTwoHandedWeapon.setEnabled(false);
        txtTypeWeapon.setText("");
        txtAmmunitionWeapon.setText("");
        txtFinesseWeapon.setText("");
        txtHeavyWeapon.setText("");
        txtLoadingWeapon.setText("");
        txtMaxWeapon.setText("");
        txtMinWeapon.setText("");
        txtNAttackWeapon.setText("");
        txtSConditionWeapon.setText("");
        txtThrownWeapon.setText("");
        txtTwoHAttackWeapon.setText("");
        txtTwoHandedWeapon.setText("");
        
        btnNewWeapon.setEnabled(true);
        btnUpdateWeapon.setEnabled(true);
        btnDeleteWeapon.setEnabled(true);
        btnCancelWeapon.setEnabled(false);
        btnSaveWeapon.setEnabled(false);
        btnExitWeapon.setEnabled(true);
    }//GEN-LAST:event_btnCancelWeaponMouseClicked

    private void jpWeaponComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jpWeaponComponentShown
        // TODO add your handling code here:
        txtAmmunitionWeapon.setEnabled(false);
        txtFinesseWeapon.setEnabled(false);
        txtHeavyWeapon.setEnabled(false);
        txtLoadingWeapon.setEnabled(false);
        txtMaxWeapon.setEnabled(false);
        txtMinWeapon.setEnabled(false);
        txtTypeWeapon.setEnabled(false);
        txtNAttackWeapon.setEnabled(false);
        txtSConditionWeapon.setEnabled(false);
        txtThrownWeapon.setEnabled(false);
        txtTwoHAttackWeapon.setEnabled(false);
        txtTwoHandedWeapon.setEnabled(false);
        txtTypeWeapon.setText("");
        txtAmmunitionWeapon.setText("");
        txtFinesseWeapon.setText("");
        txtHeavyWeapon.setText("");
        txtLoadingWeapon.setText("");
        txtMaxWeapon.setText("");
        txtMinWeapon.setText("");
        txtNAttackWeapon.setText("");
        txtSConditionWeapon.setText("");
        txtThrownWeapon.setText("");
        txtTwoHAttackWeapon.setText("");
        txtTwoHandedWeapon.setText("");
        
        btnNewWeapon.setEnabled(true);
        btnUpdateWeapon.setEnabled(true);
        btnDeleteWeapon.setEnabled(true);
        btnCancelWeapon.setEnabled(false);
        btnSaveWeapon.setEnabled(false);
        btnExitWeapon.setEnabled(true);
    }//GEN-LAST:event_jpWeaponComponentShown

    private void txtACMonsterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtACMonsterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtACMonsterActionPerformed

    private void txtChallengeMonsterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtChallengeMonsterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtChallengeMonsterActionPerformed

    private void txtNameMonsterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameMonsterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameMonsterActionPerformed

    private void jpMonsterComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jpMonsterComponentShown
        txtAlignmentMonster.setEnabled(false);
        txtACMonster.setEnabled(false);
        txtACTypeMonster.setEnabled(false);
        txtChallengeMonster.setEnabled(false);
        txtNameMonster.setEnabled(false);
        txtSyzeMonster.setEnabled(false);
        txtTypeMonster.setEnabled(false);
        txtDescriptionMonster.setEnabled(false);
        //txtSConditionMonster.setEnabled(false);
        //txtThrownMonster.setEnabled(false);
        //txtTwoHAttackMonster.setEnabled(false);
        //txtTwoHandedMonster.setEnabled(false);
        txtTypeMonster.setText("");
        txtAlignmentMonster.setText("");
        txtACMonster.setText("");
        txtACTypeMonster.setText("");
        txtChallengeMonster.setText("");
        txtNameMonster.setText("");
        txtSyzeMonster.setText("");
        txtDescriptionMonster.setText("");
        //txtSConditionMonster.setText("");
        //txtThrownMonster.setText("");
        //txtTwoHAttackMonster.setText("");
        //txtTwoHandedMonster.setText("");
        
        btnNewMonster.setEnabled(true);
        btnUpdateMonster.setEnabled(true);
        btnDeleteMonster.setEnabled(true);
        btnCancelMonster.setEnabled(false);
        btnSaveMonster.setEnabled(false);
        btnExitMonster.setEnabled(true);
    }//GEN-LAST:event_jpMonsterComponentShown

    private void btnNewMonsterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNewMonsterMouseClicked
        // TODO add your handling code here:
        txtAlignmentMonster.setEnabled(true);
        txtACMonster.setEnabled(true);
        txtACTypeMonster.setEnabled(true);
        txtChallengeMonster.setEnabled(true);
        txtNameMonster.setEnabled(true);
        txtSyzeMonster.setEnabled(true);
        txtTypeMonster.setEnabled(true);
        txtDescriptionMonster.setEnabled(true);
        //txtSConditionMonster.setEnabled(true);
        //txtThrownMonster.setEnabled(true);
        //txtTwoHAttackMonster.setEnabled(true);
        //txtTwoHandedMonster.setEnabled(true);
        txtTypeMonster.setText("");
        txtAlignmentMonster.setText("");
        txtACMonster.setText("");
        txtACTypeMonster.setText("");
        txtChallengeMonster.setText("");
        txtNameMonster.setText("");
        txtSyzeMonster.setText("");
        txtDescriptionMonster.setText("");
        //txtSConditionMonster.setText("");
        //txtThrownMonster.setText("");
        //txtTwoHAttackMonster.setText("");
        //txtTwoHandedMonster.setText("");
        
        btnNewMonster.setEnabled(false);
        btnUpdateMonster.setEnabled(false);
        btnDeleteMonster.setEnabled(false);
        btnCancelMonster.setEnabled(true);
        btnSaveMonster.setEnabled(true);
        btnExitMonster.setEnabled(false);
    }//GEN-LAST:event_btnNewMonsterMouseClicked

    private void btnUpdateMonsterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateMonsterMouseClicked
        // TODO add your handling code here:
        txtAlignmentMonster.setEnabled(true);
        txtACMonster.setEnabled(true);
        txtACTypeMonster.setEnabled(true);
        txtChallengeMonster.setEnabled(true);
        txtNameMonster.setEnabled(true);
        txtSyzeMonster.setEnabled(true);
        txtTypeMonster.setEnabled(true);
        txtDescriptionMonster.setEnabled(true);
        //txtSConditionMonster.setEnabled(true);
        //txtThrownMonster.setEnabled(true);
        //txtTwoHAttackMonster.setEnabled(true);
        //txtTwoHandedMonster.setEnabled(true);
        
        btnNewMonster.setEnabled(false);
        btnUpdateMonster.setEnabled(false);
        btnDeleteMonster.setEnabled(false);
        btnCancelMonster.setEnabled(true);
        btnSaveMonster.setEnabled(true);
        btnExitMonster.setEnabled(false);
    }//GEN-LAST:event_btnUpdateMonsterMouseClicked

    private void btnDeleteMonsterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteMonsterMouseClicked
        // TODO add your handling code here:
        
        btnNewMonster.setEnabled(false);
        btnUpdateMonster.setEnabled(false);
        btnDeleteMonster.setEnabled(false);
        btnCancelMonster.setEnabled(true);
        btnSaveMonster.setEnabled(true);
        btnExitMonster.setEnabled(false);
    }//GEN-LAST:event_btnDeleteMonsterMouseClicked

    private void btnSaveMonsterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSaveMonsterMouseClicked
        // TODO add your handling code here:
        txtAlignmentMonster.setEnabled(false);
        txtACMonster.setEnabled(false);
        txtACTypeMonster.setEnabled(false);
        txtChallengeMonster.setEnabled(false);
        txtNameMonster.setEnabled(false);
        txtSyzeMonster.setEnabled(false);
        txtTypeMonster.setEnabled(false);
        txtDescriptionMonster.setEnabled(true);
        //txtSConditionMonster.setEnabled(false);
        //txtThrownMonster.setEnabled(false);
        //txtTwoHAttackMonster.setEnabled(false);
        //txtTwoHandedMonster.setEnabled(false);
        txtTypeMonster.setText("");
        txtAlignmentMonster.setText("");
        txtACMonster.setText("");
        txtACTypeMonster.setText("");
        txtChallengeMonster.setText("");
        txtNameMonster.setText("");
        txtSyzeMonster.setText("");
        txtDescriptionMonster.setText("");
        //txtSConditionMonster.setText("");
        //txtThrownMonster.setText("");
        //txtTwoHAttackMonster.setText("");
        //txtTwoHandedMonster.setText("");
        
        btnNewMonster.setEnabled(true);
        btnUpdateMonster.setEnabled(true);
        btnDeleteMonster.setEnabled(true);
        btnCancelMonster.setEnabled(false);
        btnSaveMonster.setEnabled(false);
        btnExitMonster.setEnabled(true);
    }//GEN-LAST:event_btnSaveMonsterMouseClicked

    private void btnCancelMonsterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelMonsterMouseClicked
        // TODO add your handling code here:
        txtAlignmentMonster.setEnabled(false);
        txtACMonster.setEnabled(false);
        txtACTypeMonster.setEnabled(false);
        txtChallengeMonster.setEnabled(false);
        txtNameMonster.setEnabled(false);
        txtSyzeMonster.setEnabled(false);
        txtTypeMonster.setEnabled(false);
        txtDescriptionMonster.setEnabled(false);
        //txtSConditionMonster.setEnabled(false);
        //txtThrownMonster.setEnabled(false);
        //txtTwoHAttackMonster.setEnabled(false);
        //txtTwoHandedMonster.setEnabled(false);
        txtTypeMonster.setText("");
        txtAlignmentMonster.setText("");
        txtACMonster.setText("");
        txtACTypeMonster.setText("");
        txtChallengeMonster.setText("");
        txtNameMonster.setText("");
        txtSyzeMonster.setText("");
        txtDescriptionMonster.setText("");
        //txtSConditionMonster.setText("");
        //txtThrownMonster.setText("");
        //txtTwoHAttackMonster.setText("");
        //txtTwoHandedMonster.setText("");
        
        btnNewMonster.setEnabled(true);
        btnUpdateMonster.setEnabled(true);
        btnDeleteMonster.setEnabled(true);
        btnCancelMonster.setEnabled(false);
        btnSaveMonster.setEnabled(false);
        btnExitMonster.setEnabled(true);
    }//GEN-LAST:event_btnCancelMonsterMouseClicked

    private void txtAttackBRaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAttackBRaceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAttackBRaceActionPerformed

    private void jpRaceComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jpRaceComponentShown
        // TODO add your handling code here:
        txtAttackBRace.setEnabled(false);
        txtLanguageRace.setEnabled(false);
        txtSpeedRace.setEnabled(false);
        //txtLoreTraitRace.setEnabled(false);
        txtNameRace.setEnabled(false);
        //txtTraitRace.setEnabled(false);
        txtAttackBRace.setText("");
        txtLanguageRace.setText("");
        txtSpeedRace.setText("");
        //txtLoreTraitRace.setText("");
        txtNameRace.setText("");
        //txtTraitRace.setText("");
        
        btnNewRace.setEnabled(true);
        btnUpdateRace.setEnabled(true);
        btnDeleteRace.setEnabled(true);
        btnCancelRace.setEnabled(false);
        btnSaveRace.setEnabled(false);
        btnExitRace.setEnabled(true);
    }//GEN-LAST:event_jpRaceComponentShown

    private void btnNewRaceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNewRaceMouseClicked
        // TODO add your handling code here:
        txtAttackBRace.setEnabled(true);
        txtLanguageRace.setEnabled(true);
        txtSpeedRace.setEnabled(true);
        //txtLoreTraitRace.setEnabled(true);
        txtNameRace.setEnabled(true);
        //txtTraitRace.setEnabled(true);
        txtAttackBRace.setText("");
        txtLanguageRace.setText("");
        txtSpeedRace.setText("");
        //txtLoreTraitRace.setText("");
        txtNameRace.setText("");
        //txtTraitRace.setText("");
        
        btnNewRace.setEnabled(false);
        btnUpdateRace.setEnabled(false);
        btnDeleteRace.setEnabled(false);
        btnCancelRace.setEnabled(true);
        btnSaveRace.setEnabled(true);
        btnExitRace.setEnabled(false);
    }//GEN-LAST:event_btnNewRaceMouseClicked

    private void btnUpdateRaceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateRaceMouseClicked
        // TODO add your handling code here:
        txtAttackBRace.setEnabled(true);
        txtLanguageRace.setEnabled(true);
        txtSpeedRace.setEnabled(true);
        //txtLoreTraitRace.setEnabled(true);
        txtNameRace.setEnabled(true);
        //txtTraitRace.setEnabled(true);
        
        btnNewRace.setEnabled(false);
        btnUpdateRace.setEnabled(false);
        btnDeleteRace.setEnabled(false);
        btnCancelRace.setEnabled(true);
        btnSaveRace.setEnabled(true);
        btnExitRace.setEnabled(false);
    }//GEN-LAST:event_btnUpdateRaceMouseClicked

    private void btnDeleteRaceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteRaceMouseClicked
        // TODO add your handling code here:
        btnNewRace.setEnabled(false);
        btnUpdateRace.setEnabled(false);
        btnDeleteRace.setEnabled(false);
        btnCancelRace.setEnabled(true);
        btnSaveRace.setEnabled(true);
        btnExitRace.setEnabled(false);
    }//GEN-LAST:event_btnDeleteRaceMouseClicked

    private void btnSaveRaceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSaveRaceMouseClicked
        // TODO add your handling code here:
        txtAttackBRace.setEnabled(false);
        txtLanguageRace.setEnabled(false);
        txtSpeedRace.setEnabled(false);
        //txtLoreTraitRace.setEnabled(false);
        txtNameRace.setEnabled(false);
        //txtTraitRace.setEnabled(false);
        txtAttackBRace.setText("");
        txtLanguageRace.setText("");
        txtSpeedRace.setText("");
        //txtLoreTraitRace.setText("");
        txtNameRace.setText("");
        //txtTraitRace.setText("");
        
        btnNewRace.setEnabled(true);
        btnUpdateRace.setEnabled(true);
        btnDeleteRace.setEnabled(true);
        btnCancelRace.setEnabled(false);
        btnSaveRace.setEnabled(false);
        btnExitRace.setEnabled(true);
    }//GEN-LAST:event_btnSaveRaceMouseClicked

    private void btnCancelRaceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelRaceMouseClicked
        // TODO add your handling code here:
        txtAttackBRace.setEnabled(false);
        txtLanguageRace.setEnabled(false);
        txtSpeedRace.setEnabled(false);
        //txtLoreTraitRace.setEnabled(false);
        txtNameRace.setEnabled(false);
        //txtTraitRace.setEnabled(false);
        txtAttackBRace.setText("");
        txtLanguageRace.setText("");
        txtSpeedRace.setText("");
        //txtLoreTraitRace.setText("");
        txtNameRace.setText("");
        //txtTraitRace.setText("");
        
        btnNewRace.setEnabled(true);
        btnUpdateRace.setEnabled(true);
        btnDeleteRace.setEnabled(true);
        btnCancelRace.setEnabled(false);
        btnSaveRace.setEnabled(false);
        btnExitRace.setEnabled(true);
    }//GEN-LAST:event_btnCancelRaceMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmVault.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmVault.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmVault.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmVault.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmVault().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnCancelArmor;
    private javax.swing.JButton btnCancelMonster;
    private javax.swing.JButton btnCancelRace;
    private javax.swing.JButton btnCancelWeapon;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnDeleteArmor;
    private javax.swing.JButton btnDeleteMonster;
    private javax.swing.JButton btnDeleteRace;
    private javax.swing.JButton btnDeleteWeapon;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnExitArmor;
    private javax.swing.JButton btnExitMonster;
    private javax.swing.JButton btnExitRace;
    private javax.swing.JButton btnExitWeapon;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnNewArmor;
    private javax.swing.JButton btnNewMonster;
    private javax.swing.JButton btnNewRace;
    private javax.swing.JButton btnNewWeapon;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSaveArmor;
    private javax.swing.JButton btnSaveMonster;
    private javax.swing.JButton btnSaveRace;
    private javax.swing.JButton btnSaveWeapon;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnUpdateArmor;
    private javax.swing.JButton btnUpdateMonster;
    private javax.swing.JButton btnUpdateRace;
    private javax.swing.JButton btnUpdateWeapon;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JPanel jpAdventureGear;
    private javax.swing.JPanel jpArmor;
    private javax.swing.JPanel jpAttribute;
    private javax.swing.JPanel jpClass;
    private javax.swing.JPanel jpItem;
    private javax.swing.JPanel jpMonster;
    private javax.swing.JPanel jpRace;
    private javax.swing.JPanel jpSpell;
    private javax.swing.JPanel jpVault;
    private javax.swing.JPanel jpWeapon;
    private javax.swing.JTabbedPane jtVault;
    private javax.swing.JLabel lblACBonus;
    private javax.swing.JLabel lblACMonster;
    private javax.swing.JLabel lblACTypeMonster;
    private javax.swing.JLabel lblActionsMonster;
    private javax.swing.JLabel lblAlignment;
    private javax.swing.JLabel lblAmmunitionWeapon;
    private javax.swing.JLabel lblAttackBRace;
    private javax.swing.JLabel lblChallengeMonster;
    private javax.swing.JLabel lblDescriptionGear;
    private javax.swing.JLabel lblDescriptionMonster;
    private javax.swing.JLabel lblFinesseWeapon;
    private javax.swing.JLabel lblHeavyWeapon;
    private javax.swing.JLabel lblLActions;
    private javax.swing.JLabel lblLanguageRace;
    private javax.swing.JLabel lblLoadWeapon;
    private javax.swing.JLabel lblLoreTraitRace;
    private javax.swing.JLabel lblMaxWeapon;
    private javax.swing.JLabel lblMinWeapon;
    private javax.swing.JLabel lblModifierArmor;
    private javax.swing.JLabel lblNAttackWeapon;
    private javax.swing.JLabel lblNameMonster;
    private javax.swing.JLabel lblNameRace;
    private javax.swing.JLabel lblReactionsMonster;
    private javax.swing.JLabel lblSConditionWeapon;
    private javax.swing.JLabel lblSTraitsMonster;
    private javax.swing.JLabel lblSpeedRace;
    private javax.swing.JLabel lblStealthDArmor;
    private javax.swing.JLabel lblStrenghtRArmor;
    private javax.swing.JLabel lblSyzeMonster;
    private javax.swing.JLabel lblThrownWeapon;
    private javax.swing.JLabel lblTraitRace;
    private javax.swing.JLabel lblTwoHAttackWeapon;
    private javax.swing.JLabel lblTwoHandedWeapon;
    private javax.swing.JLabel lblTypeArmor;
    private javax.swing.JLabel lblTypeGear;
    private javax.swing.JLabel lblTypeMonster;
    private javax.swing.JLabel lblTypeWeapon;
    private javax.swing.JToolBar tbAdventureGear;
    private javax.swing.JToolBar tbArmor;
    private javax.swing.JToolBar tbMonster;
    private javax.swing.JTable tblArmor;
    private javax.swing.JTable tblGear;
    private javax.swing.JTable tblMonster;
    private javax.swing.JTable tblRace;
    private javax.swing.JTable tblWeapon;
    private javax.swing.JTextField txtACBonus;
    private javax.swing.JTextField txtACMonster;
    private javax.swing.JTextField txtACTypeMonster;
    private javax.swing.JTextField txtAlignmentMonster;
    private javax.swing.JTextField txtAmmunitionWeapon;
    private javax.swing.JTextField txtAttackBRace;
    private javax.swing.JTextField txtChallengeMonster;
    private javax.swing.JTextArea txtDescription;
    private javax.swing.JTextArea txtDescriptionMonster;
    private javax.swing.JTextField txtFinesseWeapon;
    private javax.swing.JTextField txtHeavyWeapon;
    private javax.swing.JTextField txtLanguageRace;
    private javax.swing.JTextField txtLoadingWeapon;
    private javax.swing.JTextField txtMaxWeapon;
    private javax.swing.JTextField txtMinWeapon;
    private javax.swing.JTextField txtModifierArmor;
    private javax.swing.JTextField txtNAttackWeapon;
    private javax.swing.JTextField txtNameMonster;
    private javax.swing.JTextField txtNameRace;
    private javax.swing.JTextField txtSConditionWeapon;
    private javax.swing.JTextField txtSpeedRace;
    private javax.swing.JTextField txtStealthDArmor;
    private javax.swing.JTextField txtStrenghtRArmor;
    private javax.swing.JTextField txtSyzeMonster;
    private javax.swing.JTextField txtThrownWeapon;
    private javax.swing.JTextField txtTwoHAttackWeapon;
    private javax.swing.JTextField txtTwoHandedWeapon;
    private javax.swing.JTextField txtTypeArmor;
    private javax.swing.JTextField txtTypeGear;
    private javax.swing.JTextField txtTypeMonster;
    private javax.swing.JTextField txtTypeWeapon;
    // End of variables declaration//GEN-END:variables
}
